version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: todo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: todo_db
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todo_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - todo-network

  todo-app:
    build: .
    container_name: todo-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/todo_db
      SPRING_DATASOURCE_USERNAME: todo_user
      SPRING_DATASOURCE_PASSWORD: todo_pass
      JWT_SECRET: your_jwt_secret_key_which_should_be_at_least_64_characters_long_for_security
      JWT_EXPIRATION: 86400000
    depends_on:
      - mysql
    networks:
      - todo-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  todo-network:
    driver: bridge 